language: python
dist: xenial
python:
  - "3.8"

before_install:
  - pip install poetry

install:
  - poetry install -E compat -E extension-backend-ray

script:
  - poetry run python3 -m pytest tests
