[tool.poetry]
name = "radcad"
version = "0.6.0"
description = "A cadCAD implementation, for dynamical systems modelling & simulation"
authors = ["Benjamin Scholtz <ben@bitsofether.com>"]
packages = [
    { include = "radcad" },
]

[tool.poetry.dependencies]
python = ">=3.7,<=3.9"
pathos = "^0.2.7"
pandas = "^1.0.0"
cadCAD = { version = "^0.4.23", optional = true }
ray = { version = "^1.1.0", optional = true }
boto3 = { version = "^1.16.43", optional = true }
yapapi = { version = "^0.5.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
coveralls = "^2.2.0"
pytest-cov = "^2.10.1"
pytest-benchmark = "^3.2.3"
matplotlib = "^3.3.3"
plotly = "^4.14.1"
ipykernel = "^5.4.2"
celluloid = "^0.2.0"
ipywidgets = ">=7.5"
memory-profiler = "^0.58.0"
black = "^20.8b1"
streamlit = "^0.75.0"
pytest-monitor = "^1.5.0"
tables = "^3.6.1"
cadCAD = "^0.4.23"
ray = "^1.1.0"
boto3 = "^1.16.43"
yapapi = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
compat = ["cadCAD"]
extension-backend-ray = ["ray", "boto3"]
extension-backend-golem = ["yapapi"]
